services:
  geth:
    container_name: 'poa-${NETWORK_TYPE:-mainnet}-validator-2'
    entrypoint: entrypoints/start-validator.sh
    env_file:
      - ../chain-poa/envs/validator-2.env
    volumes:
      - ../../data/${NETWORK_TYPE:-mainnet}/validator-2:/app/data
      - ../../configs/genesis.json:/app/genesis.json
      - ../../configs/config.toml:/app/config.toml
  netstats-api:
    container_name: 'poa-${NETWORK_TYPE:-mainnet}-netstats-api-2'
    links:
      - geth:rpc.host
    env_file:
      - ../chain-poa/envs/netstats-dashboard.env
      - ../chain-poa/envs/netstats-api.env
    environment:
      - INSTANCE_NAME=Validator 2