services:
  nginx:
    links:
      - openethereum:rpc.host
      - blockscout:explorer.host
      - eth-faucet:faucet.host
      - netstats-dashboard:status.host
    env_file:
      - ../chain-dpos/envs/nginx.env
    environment:
      - NETWORK_TYPE=${NETWORK_TYPE:-testnet}
    volumes:
      - ../chain-dpos/proxy:/etc/nginx/templates
      - ../data/proxy/conf.d:/etc/nginx/conf.d
      - ../data/proxy/docs:/var/www/docs
      - ../data/certbot/config/:/etc/nginx/ssl/:ro
      - ../data/certbot/www/:/var/www/certbot/:ro
    ports: !override
      - 80:80
      - 443:443
