networks:
  proxy:
    name: dpos-proxy

services:
  traefik:
    env_file:
      - ../chain-dpos/envs/traefik.env
    environment:
      - ACME_EMAIL=${ACME_EMAIL}
    volumes:
      - ../data/traefik/letsencrypt:/letsencrypt
      - ../chain-dpos/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ../chain-dpos/traefik/dynamic:/etc/traefik/dynamic:ro
    ports:
      - 80:80
      - 443:443
    labels:
      - traefik.enable=true
      - traefik.docker.network=dpos-proxy
