services:
  backend:
    image: ${BLOCKSCOUT_BACKEND_IMAGE:-blockscout-backend:11.2.1}
    pull_policy: always
    restart: always
    stop_grace_period: 5m
    container_name: blockscout-backend
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    expose:
      - 4000
