services:
  db-init:
    image: postgres:17
    volumes:
      - blockscout-db-data:/var/lib/postgresql/data
      - ./postgres-data-init.sh:/postgres-data-init.sh:ro
    entrypoint: ["/bin/sh", "/postgres-data-init.sh"]

  db:
    image: postgres:17
    user: 2000:2000
    shm_size: 256m
    restart: always
    container_name: db
    command: postgres -c 'max_connections=200' -c 'client_connection_check_interval=60000'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-blockscout}
      POSTGRES_USER: blockscout
    volumes:
      - blockscout-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blockscout -d ${POSTGRES_DB:-blockscout}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  blockscout-db-data:
