name: dpos-deploy-contracts

services:
  deployer:
    image: ${DPOS_DEPLOYER_IMAGE:-dpos-deployer:0.0.1}
    pull_policy: always
    container_name: dpos-deployer
    env_file:
      - ./envs/images.env
      - ./envs/dpos.chain.env
    environment:
      DPOS_RPC_URL: http://openethereum:8545
      INITIAL_VALIDATOR_ADDRESS: ${VALIDATOR_1_ADDRESS}
      INITIAL_SUPPLY_GWEI: ${INITIAL_SUPPLY_GWEI}
      CONTRACT_ADDRESSES_OUT: /app/genesis/contract-addresses.json
      CONTRACT_ARTIFACTS_OUT: /app/genesis
      VALIDATOR_KEYSTORE_DIR: /app/keys
      VALIDATOR_PASSWORD_FILE: /app/secrets/node.pwd
      ENABLE_CUSTOM_STAKING: ${ENABLE_CUSTOM_STAKING:-false}
      GTBS_STAKING_ENV: /gtbs/env/gtbs-staking.env
      DPOS_CONTRACT_ENV: /gtbs/env/dpos.contract.env
      DPOS_CHAIN_ENV: /gtbs/env/dpos.chain.env
    volumes:
      - ./genesis:/app/genesis
      - ./nodes/validator-1/keystore:/app/keys:ro
      - ./nodes/validator-1/node.pwd:/app/secrets/node.pwd:ro
      - ./envs/gtbs-staking.env:/gtbs/env/gtbs-staking.env:ro
      - ./envs/dpos.contract.env:/gtbs/env/dpos.contract.env:ro
      - ./envs/dpos.chain.env:/gtbs/env/dpos.chain.env:ro
    command: []
    networks:
      - validator

networks:
  validator:
    external: true
    name: ${COMPOSE_PROJECT_NAME:-dpos-validator-1}_default
